services:
  - type: web
    name: safeflood-api
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /q/health
    envVars:
      - key: JAVA_OPTS_APPEND
        value: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager" 