services:
  - type: web
    name: safeflood-api
    env: docker
    plan: free
    startCommand: java -jar /deployments/quarkus-run.jar
    envVars:
      - key: QUARKUS_DATASOURCE_JDBC_URL
        sync: false
      - key: QUARKUS_DATASOURCE_USERNAME
        sync: false
      - key: QUARKUS_DATASOURCE_PASSWORD
        sync: false 